language: python
cache: pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  # PyPy versions
  - "pypy"
matrix:
    include:
        - python: 3.7
          dist: xenial
          sudo: true
script:
  - python setup.py test
